//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepcopy-gen. DO NOT EDIT.

package fqdngcmap

import (
        bpf "github.com/cilium/cilium/pkg/bpf"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FqdnGCKey) DeepCopyInto(out *FqdnGCKey) {
        *out = *in
        return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FqdnGCKey.
func (in *FqdnGCKey) DeepCopy() *FqdnGCKey {
        if in == nil {
                return nil
        }
        out := new(FqdnGCKey)
        in.DeepCopyInto(out)
        return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapKey.
func (in *FqdnGCKey) DeepCopyMapKey() bpf.MapKey {
        if c := in.DeepCopy(); c != nil {
                return c
        }
        return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FqdnGCValue) DeepCopyInto(out *FqdnGCValue) {
        *out = *in
        return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FqdnGCValue.
func (in *FqdnGCValue) DeepCopy() *FqdnGCValue {
        if in == nil {
                return nil
        }
        out := new(FqdnGCValue)
        in.DeepCopyInto(out)
        return out
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapValue.
func (in *FqdnGCValue) DeepCopyMapValue() bpf.MapValue {
        if c := in.DeepCopy(); c != nil {
                return c
        }
        return nil
}
